#!/bin/bash

#Set default editor
export EDITOR='vi'

#Set language environment
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#Ser app directory for homebrew cask (no need for symlinks)
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Add coreutils from brew
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

#Set default GO environmet
export GOPATH=$HOME/Documents/dev/goprojects
export PATH=$GOPATH/bin:$PATH

#Add composer bin globaly (PHP)
#export PATH=$PATH:$HOME/.composer/vendor/bin